[window]
padding.x = 10
padding.y = 10

# removes the mac app header
decorations = "Buttonless"

# background
opacity = 0.75
blur = true


[font]
normal.family = "JetBrainsMono Nerd Font Mono"
size = 12
